AWSTemplateFormatVersion: 2010-09-09
Description: |
    Cloudformation Template for kittens carousel static website deploy on s3 through
    cloudfront and route 53
Parameters:
  KittensDomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone. e.g. clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  KittensBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub ${KittensBucket.Arn}/* # change here
#Outputs: